name: CI/CD Pull and Build

on:
  push:
    branches:
      - main

jobs:
  pull-code-and-build:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: |
          cd /var/www/mysurefit-iframes.com
          git pull origin main

      - name: Install dependencies
        run: |
          cd /var/www/mysurefit-iframes.com
          npm ci

      - name: Build
        run: |
          cd /var/www/mysurefit-iframes.com
          npm run build

      - name: Reload nginx
        run: sudo nginx -s reload
